# Generated by Django 4.2.13 on 2024-05-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.IntegerField()),
                ('column2', models.CharField(max_length=255)),
                ('column3', models.CharField(max_length=255)),
            ],
        ),
    ]
