# Generated by Django 4.2.13 on 2024-05-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='column1',
            field=models.CharField(max_length=255),
        ),
    ]
