# Generated by Django 4.2.13 on 2024-06-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
